services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v2.54.1}
    container_name: prometheus-dev
    user: "${DEV_UID:-65534}:${DEV_GID:-65534}"  # Configurable user to avoid permission issues
    ports:
      - "${BIND_IP:-127.0.0.1}:${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${PROMETHEUS_DATA_PATH}:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME}'
      - '--web.enable-lifecycle'
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - fbx-export
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-11.3.0}
    container_name: grafana-dev
    user: "${DEV_UID:-472}:${DEV_GID:-472}"  # Configurable Grafana user ID to avoid permission issues
    ports:
      - "${BIND_IP:-127.0.0.1}:${GRAFANA_PORT:-3000}:3000"
    volumes:
      - ${GRAFANA_DATA_PATH}:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    secrets:
      - grafana_admin_user
      - grafana_admin_password
    environment:
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/grafana_admin_user
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: "no"
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
      - fbx-export
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  fbx-export:
    name: ${DOCKER_NETWORK_NAME:-fbx-export-dev}
    driver: bridge

secrets:
  grafana_admin_user:
    file: ./secrets/grafana_admin_user.txt
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt