services:
  freebox-exporter:
    build:
      context: ..
      dockerfile: Dockerfile
      network: host
    container_name: freebox-exporter
    user: 65534:65534
    ports:
      - "${BIND_IP:-127.0.0.1}:${FBX_EXPORTER_PORT:-9091}:9091"
    secrets:
      - freebox_token
    # Override default CMD with additional flags
    command: [
      "-hostDetails",
      # "-debug",
      "-listen", ":9091",
      "/run/secrets/freebox_token"
    ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9091/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - fbx-export

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v2.54.1}
    container_name: prometheus-fbx
    user: "65534:65534"  # nobody:nobody user to avoid permission issues
    ports:
      - "${BIND_IP:-127.0.0.1}:${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME:-30d}'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    depends_on:
      freebox-exporter:
        condition: service_healthy
    networks:
      - fbx-export
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-11.3.0}
    container_name: grafana-fbx
    user: "472:472"  # Default Grafana user ID to avoid permission issues
    ports:
      - "${BIND_IP:-127.0.0.1}:${GRAFANA_PORT:-3000}:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    secrets:
      - grafana_admin_user
      - grafana_admin_password
    environment:
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/grafana_admin_user
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
      - fbx-export
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  fbx-export:
    name: ${DOCKER_NETWORK_NAME:-fbx-export-prod}
    driver: bridge
  traefik:
    name: "traefik-lan"
    external: true
  
secrets:
  freebox_token:
    file: ./secrets/freebox_token.json
  grafana_admin_user:
    file: ./secrets/grafana_admin_user.txt
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt
