# Prometheus configuration for production FBX Exporter deployment
# Place this file in the same directory as your docker-compose.prod.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # Add alerting rules here if needed
  # - "alert_rules.yml"

scrape_configs:
  # Freebox Exporter
  - job_name: 'freebox-exporter'
    static_configs:
      - targets: ['freebox-exporter:9091']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics

# Optional: Alertmanager configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093